# CapCut-style Caption Templates & Famous Creator Fonts Library

FAMOUS_FONTS = [
    {"name": "Montserrat", "family": "'Montserrat', sans-serif", "ass": "Montserrat", "tag": "Viral Standard"},
    {"name": "Bebas Neue", "family": "'Bebas Neue', sans-serif", "ass": "Bebas Neue", "tag": "High Energy"},
    {"name": "Impact", "family": "Impact, Arial Black, sans-serif", "ass": "Impact", "tag": "Bold Punch"},
    {"name": "Anton", "family": "'Anton', sans-serif", "ass": "Anton", "tag": "Ultra Bold"},
    {"name": "Bangers", "family": "'Bangers', cursive", "ass": "Bangers", "tag": "MrBeast Comic"},
    {"name": "Poppins", "family": "'Poppins', sans-serif", "ass": "Poppins", "tag": "Clean Modern"},
    {"name": "Oswald", "family": "'Oswald', sans-serif", "ass": "Oswald", "tag": "Editorial"},
    {"name": "Cinzel", "family": "'Cinzel', serif", "ass": "Cinzel", "tag": "Cinematic Title"},
    {"name": "Playfair Display", "family": "'Playfair Display', serif", "ass": "Playfair Display", "tag": "Luxury Serif"},
    {"name": "Orbitron", "family": "'Orbitron', sans-serif", "ass": "Orbitron", "tag": "Sci-Fi Cyber"},
    {"name": "Inter", "family": "'Inter', sans-serif", "ass": "Inter", "tag": "Minimalist"},
    {"name": "Pacifico", "family": "'Pacifico', cursive", "ass": "Pacifico", "tag": "Creative Script"},
    {"name": "Syne", "family": "'Syne', sans-serif", "ass": "Syne", "tag": "Trend Avant-Garde"},
    {"name": "Rubik", "family": "'Rubik', sans-serif", "ass": "Rubik", "tag": "Friendly Punch"}
]

# Color palette for active word highlighting
HIGHLIGHT_COLORS = {
    "yellow": {"name": "Neon Yellow", "hex": "#facc15", "ass": "&H0000FFFF&"},
    "green": {"name": "Toxic Green", "hex": "#4ade80", "ass": "&H0000FF00&"},
    "cyan": {"name": "Electric Cyan", "hex": "#38bdf8", "ass": "&H00FFFF00&"},
    "pink": {"name": "Hot Magenta", "hex": "#f43f5e", "ass": "&H00FF00EA&"},
    "orange": {"name": "Fiery Orange", "hex": "#fb923c", "ass": "&H000088FF&"},
    "purple": {"name": "Vibrant Violet", "hex": "#c084fc", "ass": "&H00FF55D4&"},
    "red": {"name": "Crimson Fire", "hex": "#ef4444", "ass": "&H000000FF&"},
    "white": {"name": "Luminous White", "hex": "#ffffff", "ass": "&H00FFFFFF&"}
}

# 78+ Premade Animated Caption Templates
TEMPLATES = {
    # ==========================================
    # 0. HYBRID & MULTI-FONT CREATOR PAIRS (10)
    # ==========================================
    "smooth_cross": {
        "id": "smooth_cross",
        "name": "Smooth Cross (Sans + Script)",
        "category": "Hybrid",
        "is_multi_font": True,
        "body_font": "Montserrat",
        "hero_font": "Pacifico",
        "fontname": "Montserrat",
        "fontsize": 66,
        "primary_color": "&H00FFFFFF&",       # Base: White
        "secondary_color": "&H00FF55D4&",     # Hero: Vibrant Purple
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 1,
        "italic": 0,
        "hero_italic": 1,
        "hero_scale": 125,
        "outline": 4.0,
        "shadow": 2.5,
        "alignment": 2,
        "margin_v": 80,
        "animation": "pop",
        "badge": "Hybrid",
        "preview_text": "Smooth Cross",
        "preview_highlight": "Cross"
    },
    "hero_spotlight": {
        "id": "hero_spotlight",
        "name": "Hero Spotlight (Minimal + Bold)",
        "category": "Hybrid",
        "is_multi_font": True,
        "body_font": "Inter",
        "hero_font": "Anton",
        "fontname": "Inter",
        "fontsize": 64,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000FFFF&",     # Yellow
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 0,
        "italic": 0,
        "hero_italic": 0,
        "hero_scale": 130,
        "outline": 4.0,
        "shadow": 3.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "zoom",
        "badge": "Hybrid",
        "preview_text": "Type your Hero Text",
        "preview_highlight": "Hero Text"
    },
    "creator_hierarchy": {
        "id": "creator_hierarchy",
        "name": "Creator 3-Line Hierarchy",
        "category": "Hybrid",
        "is_multi_font": True,
        "body_font": "Inter",
        "hero_font": "Bebas Neue",
        "fontname": "Inter",
        "fontsize": 62,
        "primary_color": "&H00FFFFFF&",       # White
        "secondary_color": "&H00FFFF00&",     # Cyan
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 1,
        "italic": 0,
        "hero_italic": 0,
        "hero_scale": 135,
        "outline": 4.5,
        "shadow": 3.0,
        "alignment": 2,
        "margin_v": 85,
        "animation": "bounce",
        "badge": "Hierarchy",
        "preview_text": "Life is shorter than reality",
        "preview_highlight": "shorter"
    },
    "serif_punch": {
        "id": "serif_punch",
        "name": "Luxury Serif & Punch",
        "category": "Hybrid",
        "is_multi_font": True,
        "body_font": "Playfair Display",
        "hero_font": "Bebas Neue",
        "fontname": "Playfair Display",
        "fontsize": 64,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H000088FF&",     # Orange/Gold
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 0,
        "italic": 1,
        "hero_italic": 0,
        "hero_scale": 128,
        "outline": 3.5,
        "shadow": 2.5,
        "alignment": 2,
        "margin_v": 80,
        "animation": "slide",
        "badge": "Hybrid",
        "preview_text": "Here is the logic behind",
        "preview_highlight": "logic"
    },
    "mrbeast_duo": {
        "id": "mrbeast_duo",
        "name": "MrBeast Comic Duo",
        "category": "Hybrid",
        "is_multi_font": True,
        "body_font": "Poppins",
        "hero_font": "Bangers",
        "fontname": "Poppins",
        "fontsize": 66,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000FFFF&",     # Yellow
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 1,
        "italic": 0,
        "hero_italic": 0,
        "hero_scale": 130,
        "outline": 5.0,
        "shadow": 3.5,
        "alignment": 2,
        "margin_v": 80,
        "animation": "pop",
        "badge": "Boom",
        "preview_text": "One move changes everything",
        "preview_highlight": "changes"
    },
    "devin_jatho_fx": {
        "id": "devin_jatho_fx",
        "name": "Devin Jatho Cyber Glow",
        "category": "Hybrid",
        "is_multi_font": True,
        "body_font": "Inter",
        "hero_font": "Orbitron",
        "fontname": "Orbitron",
        "fontsize": 62,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H00FFFF00&",     # Cyan
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 1,
        "italic": 0,
        "hero_italic": 0,
        "hero_scale": 120,
        "outline": 4.5,
        "shadow": 3.5,
        "alignment": 2,
        "margin_v": 80,
        "animation": "glow",
        "badge": "Cyber",
        "preview_text": "DEVIN JATHO EFFECT",
        "preview_highlight": "EFFECT"
    },
    "apple_clean_duo": {
        "id": "apple_clean_duo",
        "name": "Clean Apple Animation",
        "category": "Hybrid",
        "is_multi_font": True,
        "body_font": "Inter",
        "hero_font": "Montserrat",
        "fontname": "Inter",
        "fontsize": 58,
        "primary_color": "&H00E0E0E0&",
        "secondary_color": "&H00FFFFFF&",
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 0,
        "italic": 0,
        "hero_italic": 0,
        "hero_scale": 115,
        "outline": 2.5,
        "shadow": 1.5,
        "alignment": 2,
        "margin_v": 75,
        "animation": "fade",
        "badge": "Apple",
        "preview_text": "Clean apple style text",
        "preview_highlight": "style"
    },
    "shiny_metallic": {
        "id": "shiny_metallic",
        "name": "Shiny Chrome & Script",
        "category": "Hybrid",
        "is_multi_font": True,
        "body_font": "Montserrat",
        "hero_font": "Pacifico",
        "fontname": "Montserrat",
        "fontsize": 64,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H00FFFF00&",     # Cyan
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 1,
        "italic": 0,
        "hero_italic": 1,
        "hero_scale": 125,
        "outline": 4.0,
        "shadow": 3.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "glow",
        "badge": "Shiny",
        "preview_text": "Metallic Text Design",
        "preview_highlight": "Metallic"
    },
    "shadow_contrast": {
        "id": "shadow_contrast",
        "name": "Shadow Effect Duo",
        "category": "Hybrid",
        "is_multi_font": True,
        "body_font": "Inter",
        "hero_font": "Impact",
        "fontname": "Inter",
        "fontsize": 68,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000FFFF&",     # Yellow
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 1,
        "italic": 0,
        "hero_italic": 0,
        "hero_scale": 130,
        "outline": 5.0,
        "shadow": 4.0,
        "alignment": 2,
        "margin_v": 85,
        "animation": "bounce",
        "badge": "Shadow",
        "preview_text": "Shadow Text Effect",
        "preview_highlight": "Shadow"
    },
    "kinetic_duo": {
        "id": "kinetic_duo",
        "name": "Kinetic Drift & Punch",
        "category": "Hybrid",
        "is_multi_font": True,
        "body_font": "Oswald",
        "hero_font": "Anton",
        "fontname": "Oswald",
        "fontsize": 65,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000FF00&",     # Green
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 1,
        "italic": 0,
        "hero_italic": 0,
        "hero_scale": 125,
        "outline": 4.5,
        "shadow": 2.5,
        "alignment": 2,
        "margin_v": 80,
        "animation": "slide",
        "badge": "Sliding",
        "preview_text": "Here is the sliding text",
        "preview_highlight": "sliding"
    },

    # ==========================================
    # 1. VIRAL CREATOR STYLES (12)
    # ==========================================
    "hormozi_classic": {
        "id": "hormozi_classic",
        "name": "Alex Hormozi Classic",
        "category": "Creators",
        "fontname": "Montserrat, Impact, Arial Black",
        "fontsize": 68,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000FFFF&",
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 1,
        "italic": 0,
        "outline": 4.5,
        "shadow": 2.5,
        "alignment": 2,
        "margin_v": 80,
        "animation": "bounce",
        "badge": "Viral",
        "preview_text": "THE SECRET TO WEALTH",
        "preview_highlight": "WEALTH"
    },
    "mrbeast_comic": {
        "id": "mrbeast_comic",
        "name": "MrBeast Boom Comic",
        "category": "Creators",
        "fontname": "Bangers, Impact, Arial Black",
        "fontsize": 76,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000FFFF&",
        "outline_color": "&H00000000&",
        "back_color": "&H000000FF&",
        "bold": 1,
        "italic": 0,
        "outline": 5.0,
        "shadow": 4.0,
        "alignment": 2,
        "margin_v": 85,
        "animation": "comic_pop",
        "badge": "Viral",
        "preview_text": "I GAVE AWAY $1,000,000",
        "preview_highlight": "$1,000,000"
    },
    "iman_gadzhi": {
        "id": "iman_gadzhi",
        "name": "Iman Gadzhi Noir",
        "category": "Creators",
        "fontname": "Playfair Display, Georgia, serif",
        "fontsize": 64,
        "primary_color": "&H00F5F5F5&",
        "secondary_color": "&H00D4AF37&", # Gold
        "outline_color": "&H00111111&",
        "back_color": "&H60000000&",
        "bold": 0,
        "italic": 1,
        "outline": 2.0,
        "shadow": 2.0,
        "alignment": 2,
        "margin_v": 90,
        "animation": "smooth_fade",
        "badge": "Pro",
        "preview_text": "The monk mode formula",
        "preview_highlight": "formula"
    },
    "ali_abdaal": {
        "id": "ali_abdaal",
        "name": "Ali Abdaal Clean",
        "category": "Creators",
        "fontname": "Poppins, Inter, sans-serif",
        "fontsize": 58,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000FFFF&",
        "outline_color": "&H001E1E1E&",
        "back_color": "&H50000000&",
        "bold": 1,
        "italic": 0,
        "outline": 2.5,
        "shadow": 1.5,
        "alignment": 2,
        "margin_v": 75,
        "animation": "micro_bounce",
        "badge": "Clean",
        "preview_text": "How to feel productive",
        "preview_highlight": "productive"
    },
    "magnates_media": {
        "id": "magnates_media",
        "name": "Magnates Media Gold",
        "category": "Creators",
        "fontname": "Cinzel, Times New Roman, serif",
        "fontsize": 66,
        "primary_color": "&H00E0E0E0&",
        "secondary_color": "&H0032CD32&",
        "outline_color": "&H00000000&",
        "back_color": "&H0000D7FF&", # Gold aura
        "bold": 1,
        "italic": 0,
        "outline": 3.0,
        "shadow": 5.0,
        "alignment": 2,
        "margin_v": 85,
        "animation": "glow_pulse",
        "badge": "Pro",
        "preview_text": "THE BILLION DOLLAR EMPIRE",
        "preview_highlight": "EMPIRE"
    },
    "dan_koe": {
        "id": "dan_koe",
        "name": "Dan Koe Minimalist",
        "category": "Creators",
        "fontname": "Inter, Arial, sans-serif",
        "fontsize": 52,
        "primary_color": "&H00EAEAEA&",
        "secondary_color": "&H00FFFFFF&",
        "outline_color": "&H000A0A0A&",
        "back_color": "&HAA000000&",
        "bold": 0,
        "italic": 0,
        "outline": 1.0,
        "shadow": 1.0,
        "alignment": 2,
        "margin_v": 70,
        "animation": "clean",
        "badge": "Pro",
        "preview_text": "Focus on the long game",
        "preview_highlight": "game"
    },
    "cody_luxury": {
        "id": "cody_luxury",
        "name": "Cody Luxury Dark",
        "category": "Creators",
        "fontname": "Bebas Neue, Montserrat",
        "fontsize": 72,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000BFFF&", # Amber
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 1,
        "italic": 0,
        "outline": 3.5,
        "shadow": 3.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "bounce",
        "badge": "Pro",
        "preview_text": "UNSTOPPABLE MOMENTUM",
        "preview_highlight": "MOMENTUM"
    },
    "tiktok_hook": {
        "id": "tiktok_hook",
        "name": "TikTok Viral Hook",
        "category": "Creators",
        "fontname": "Anton, Impact",
        "fontsize": 74,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000FF00&", # Neon Green
        "outline_color": "&H00000000&",
        "back_color": "&H90000000&",
        "bold": 1,
        "italic": 0,
        "outline": 5.0,
        "shadow": 3.0,
        "alignment": 5, # Center
        "margin_v": 0,
        "animation": "word_zoom",
        "badge": "Viral",
        "preview_text": "WAIT FOR IT...",
        "preview_highlight": "WAIT"
    },
    "shorts_viral_pop": {
        "id": "shorts_viral_pop",
        "name": "Shorts Viral Pop",
        "category": "Creators",
        "fontname": "Montserrat, Arial Black",
        "fontsize": 70,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H00FF00EA&", # Magenta
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 1,
        "italic": 0,
        "outline": 4.0,
        "shadow": 3.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "bounce",
        "badge": "Viral",
        "preview_text": "DO NOT SKIP THIS",
        "preview_highlight": "SKIP"
    },
    "cinema_master": {
        "id": "cinema_master",
        "name": "Cinema Master 4K",
        "category": "Creators",
        "fontname": "Cinzel, Georgia",
        "fontsize": 60,
        "primary_color": "&H00F0F0F0&",
        "secondary_color": "&H00FFFF00&", # Cyan
        "outline_color": "&H00000000&",
        "back_color": "&H70000000&",
        "bold": 1,
        "italic": 0,
        "outline": 2.5,
        "shadow": 4.0,
        "alignment": 2,
        "margin_v": 90,
        "animation": "smooth_fade",
        "badge": "Pro",
        "preview_text": "A STORY OF RESILIENCE",
        "preview_highlight": "RESILIENCE"
    },
    "youtube_story": {
        "id": "youtube_story",
        "name": "YouTube Documentary",
        "category": "Creators",
        "fontname": "Oswald, Montserrat",
        "fontsize": 65,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000A5FF&", # Orange
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 1,
        "italic": 0,
        "outline": 3.5,
        "shadow": 3.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "bounce",
        "badge": "Pro",
        "preview_text": "THE TURNING POINT",
        "preview_highlight": "POINT"
    },
    "vox_explainer": {
        "id": "vox_explainer",
        "name": "Vox Explainer Style",
        "category": "Creators",
        "fontname": "Bebas Neue, Poppins",
        "fontsize": 68,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000FFFF&", # Yellow
        "outline_color": "&H00151515&",
        "back_color": "&H80000000&",
        "bold": 1,
        "italic": 0,
        "outline": 3.0,
        "shadow": 2.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "micro_bounce",
        "badge": "Pro",
        "preview_text": "WHY THIS MATTERS NOW",
        "preview_highlight": "MATTERS"
    },

    # ==========================================
    # 2. POP, BOUNCE & ELASTIC (10)
    # ==========================================
    "word_pop": {
        "id": "word_pop",
        "name": "Word Pop Center Punch",
        "category": "Bounce",
        "fontname": "Impact, Arial Black, Montserrat",
        "fontsize": 92,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000E5FF&",
        "outline_color": "&H00000000&",
        "back_color": "&H90000000&",
        "bold": 1,
        "italic": 0,
        "outline": 6.0,
        "shadow": 4.0,
        "alignment": 5, # Middle Center
        "margin_v": 0,
        "animation": "word_zoom",
        "badge": "Trending",
        "preview_text": "QUICK",
        "preview_highlight": "QUICK"
    },
    "elastic_snap": {
        "id": "elastic_snap",
        "name": "Elastic Snap",
        "category": "Bounce",
        "fontname": "Montserrat, Bebas Neue",
        "fontsize": 72,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000FF7F&",
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 1,
        "italic": 0,
        "outline": 4.0,
        "shadow": 3.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "bounce",
        "badge": "Pro",
        "preview_text": "FEEL THE SNAP",
        "preview_highlight": "SNAP"
    },
    "spring_zoom": {
        "id": "spring_zoom",
        "name": "Spring Zoom Pop",
        "category": "Bounce",
        "fontname": "Anton, Montserrat",
        "fontsize": 75,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H000088FF&",
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 1,
        "italic": 0,
        "outline": 4.5,
        "shadow": 3.0,
        "alignment": 2,
        "margin_v": 85,
        "animation": "word_zoom",
        "badge": "Pro",
        "preview_text": "SPRING INTO ACTION",
        "preview_highlight": "ACTION"
    },
    "jelly_wobble": {
        "id": "jelly_wobble",
        "name": "Jelly Wobble Bounce",
        "category": "Bounce",
        "fontname": "Rubik, Bangers",
        "fontsize": 70,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H00FF1493&",
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 1,
        "italic": 0,
        "outline": 4.0,
        "shadow": 3.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "bounce",
        "badge": "Fun",
        "preview_text": "WOBBLE AND ROLL",
        "preview_highlight": "ROLL"
    },
    "rubber_band": {
        "id": "rubber_band",
        "name": "Rubber Band Stretch",
        "category": "Bounce",
        "fontname": "Bebas Neue, Impact",
        "fontsize": 76,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000FFFF&",
        "outline_color": "&H00000000&",
        "back_color": "&H90000000&",
        "bold": 1,
        "italic": 0,
        "outline": 4.5,
        "shadow": 3.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "bounce",
        "badge": "Pro",
        "preview_text": "STRETCH YOUR LIMITS",
        "preview_highlight": "LIMITS"
    },
    "bubble_pop": {
        "id": "bubble_pop",
        "name": "Bubble Pop Soft",
        "category": "Bounce",
        "fontname": "Poppins, Montserrat",
        "fontsize": 65,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H00FF69B4&",
        "outline_color": "&H00111111&",
        "back_color": "&H70000000&",
        "bold": 1,
        "italic": 0,
        "outline": 3.0,
        "shadow": 2.5,
        "alignment": 2,
        "margin_v": 80,
        "animation": "micro_bounce",
        "badge": "Clean",
        "preview_text": "Pop into clarity",
        "preview_highlight": "clarity"
    },
    "hard_slam": {
        "id": "hard_slam",
        "name": "Hard Slam Stomp",
        "category": "Bounce",
        "fontname": "Impact, Arial Black",
        "fontsize": 82,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H000000FF&", # Red
        "outline_color": "&H00000000&",
        "back_color": "&H90000000&",
        "bold": 1,
        "italic": 0,
        "outline": 5.0,
        "shadow": 4.0,
        "alignment": 2,
        "margin_v": 85,
        "animation": "word_zoom",
        "badge": "Heavy",
        "preview_text": "SLAM IT DOWN",
        "preview_highlight": "SLAM"
    },
    "micro_bounce": {
        "id": "micro_bounce",
        "name": "Micro Subtle Bounce",
        "category": "Bounce",
        "fontname": "Montserrat, Poppins",
        "fontsize": 62,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000FFCC&",
        "outline_color": "&H00000000&",
        "back_color": "&H60000000&",
        "bold": 1,
        "italic": 0,
        "outline": 3.0,
        "shadow": 2.0,
        "alignment": 2,
        "margin_v": 75,
        "animation": "micro_bounce",
        "badge": "Clean",
        "preview_text": "Subtle and precise",
        "preview_highlight": "precise"
    },
    "mega_zoom": {
        "id": "mega_zoom",
        "name": "Mega Zoom Burst",
        "category": "Bounce",
        "fontname": "Anton, Impact",
        "fontsize": 85,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H00FFD700&",
        "outline_color": "&H00000000&",
        "back_color": "&H90000000&",
        "bold": 1,
        "italic": 0,
        "outline": 5.5,
        "shadow": 4.0,
        "alignment": 5, # Center
        "margin_v": 0,
        "animation": "word_zoom",
        "badge": "Pro",
        "preview_text": "EXPLODE",
        "preview_highlight": "EXPLODE"
    },
    "stomp_impact": {
        "id": "stomp_impact",
        "name": "Stomp Impact Beat",
        "category": "Bounce",
        "fontname": "Bebas Neue, Anton",
        "fontsize": 78,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000FFFF&",
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 1,
        "italic": 0,
        "outline": 4.5,
        "shadow": 3.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "bounce",
        "badge": "Heavy",
        "preview_text": "HIT EVERY BEAT",
        "preview_highlight": "BEAT"
    },

    # ==========================================
    # 3. GLOW, NEON & ENERGY (10)
    # ==========================================
    "neon_fox": {
        "id": "neon_fox",
        "name": "Neon Magenta & Cyan (FOX)",
        "category": "Glow",
        "fontname": "Montserrat, Arial Black, Trebuchet MS",
        "fontsize": 72,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H00FF00EA&",
        "outline_color": "&H00FF5500&",
        "back_color": "&H00D400FF&",
        "bold": 1,
        "italic": 0,
        "outline": 3.0,
        "shadow": 6.0,
        "alignment": 2,
        "margin_v": 85,
        "animation": "glow_pulse",
        "badge": "Trending",
        "preview_text": "NEON FOX GLOW",
        "preview_highlight": "FOX"
    },
    "red_fire": {
        "id": "red_fire",
        "name": "Red Fire Glow (THE QUICK)",
        "category": "Glow",
        "fontname": "Arial Black, Impact, sans-serif",
        "fontsize": 70,
        "primary_color": "&H000015FF&",
        "secondary_color": "&H0000FFFF&",
        "outline_color": "&H00000088&",
        "back_color": "&H000000FF&",
        "bold": 1,
        "italic": 0,
        "outline": 4.0,
        "shadow": 6.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "fire_pulse",
        "badge": "Trending",
        "preview_text": "THE QUICK FIRE",
        "preview_highlight": "QUICK"
    },
    "electric_cyan": {
        "id": "electric_cyan",
        "name": "Electric Cyan Plasma",
        "category": "Glow",
        "fontname": "Orbitron, Montserrat",
        "fontsize": 68,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H00FFFF00&",
        "outline_color": "&H00FF8800&",
        "back_color": "&H00FFFF00&",
        "bold": 1,
        "italic": 0,
        "outline": 3.0,
        "shadow": 6.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "glow_pulse",
        "badge": "SciFi",
        "preview_text": "PLASMA LIGHTNING",
        "preview_highlight": "LIGHTNING"
    },
    "violet_aura": {
        "id": "violet_aura",
        "name": "Violet Dream Aura",
        "category": "Glow",
        "fontname": "Montserrat, Poppins",
        "fontsize": 66,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H00FF55D4&",
        "outline_color": "&H00800080&",
        "back_color": "&H00FF00EA&",
        "bold": 1,
        "italic": 0,
        "outline": 2.5,
        "shadow": 5.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "glow_pulse",
        "badge": "Glow",
        "preview_text": "VIOLET HAZE DREAM",
        "preview_highlight": "DREAM"
    },
    "golden_hour": {
        "id": "golden_hour",
        "name": "Golden Hour Ray",
        "category": "Glow",
        "fontname": "Playfair Display, Georgia",
        "fontsize": 64,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000D7FF&",
        "outline_color": "&H0000458B&",
        "back_color": "&H0000A5FF&",
        "bold": 1,
        "italic": 1,
        "outline": 2.5,
        "shadow": 5.0,
        "alignment": 2,
        "margin_v": 85,
        "animation": "glow_pulse",
        "badge": "Pro",
        "preview_text": "Golden sunlight warmth",
        "preview_highlight": "sunlight"
    },
    "toxic_emerald": {
        "id": "toxic_emerald",
        "name": "Toxic Emerald Bio",
        "category": "Glow",
        "fontname": "Impact, Montserrat",
        "fontsize": 70,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000FF00&",
        "outline_color": "&H00005500&",
        "back_color": "&H0000FF7F&",
        "bold": 1,
        "italic": 0,
        "outline": 3.5,
        "shadow": 6.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "glow_pulse",
        "badge": "Pro",
        "preview_text": "TOXIC GREEN SURGE",
        "preview_highlight": "SURGE"
    },
    "moonlight_halo": {
        "id": "moonlight_halo",
        "name": "Moonlight Halo Soft",
        "category": "Glow",
        "fontname": "Poppins, Inter",
        "fontsize": 62,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H00FFFFE0&",
        "outline_color": "&H00111111&",
        "back_color": "&H00FFFFFF&",
        "bold": 0,
        "italic": 0,
        "outline": 2.0,
        "shadow": 6.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "glow_pulse",
        "badge": "Soft",
        "preview_text": "Beneath the moon",
        "preview_highlight": "moon"
    },
    "vaporwave_sunset": {
        "id": "vaporwave_sunset",
        "name": "Vaporwave Sunset 80s",
        "category": "Glow",
        "fontname": "Righteous, Montserrat",
        "fontsize": 68,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H00FF69B4&",
        "outline_color": "&H008B008B&",
        "back_color": "&H00FFFF00&",
        "bold": 1,
        "italic": 0,
        "outline": 3.5,
        "shadow": 5.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "glow_pulse",
        "badge": "Retro",
        "preview_text": "RETRO SUNSET VIBES",
        "preview_highlight": "SUNSET"
    },
    "pulsar_core": {
        "id": "pulsar_core",
        "name": "Pulsar Star Core",
        "category": "Glow",
        "fontname": "Orbitron, Syne",
        "fontsize": 72,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000FFFF&",
        "outline_color": "&H00000088&",
        "back_color": "&H000088FF&",
        "bold": 1,
        "italic": 0,
        "outline": 3.0,
        "shadow": 6.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "glow_pulse",
        "badge": "SciFi",
        "preview_text": "COSMIC PULSE",
        "preview_highlight": "PULSE"
    },
    "laser_strike": {
        "id": "laser_strike",
        "name": "Laser Strike Red",
        "category": "Glow",
        "fontname": "Anton, Impact",
        "fontsize": 75,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H000000FF&",
        "outline_color": "&H00000000&",
        "back_color": "&H000000FF&",
        "bold": 1,
        "italic": 0,
        "outline": 4.0,
        "shadow": 7.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "fire_pulse",
        "badge": "Heavy",
        "preview_text": "TARGET ACQUIRED",
        "preview_highlight": "TARGET"
    },

    # ==========================================
    # 4. KINETIC & MOTION (10)
    # ==========================================
    "slide_up_float": {
        "id": "slide_up_float",
        "name": "Slide Up Float",
        "category": "Kinetic",
        "fontname": "Montserrat, Poppins",
        "fontsize": 65,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000FFCC&",
        "outline_color": "&H00000000&",
        "back_color": "&H70000000&",
        "bold": 1,
        "italic": 0,
        "outline": 3.0,
        "shadow": 2.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "slide_up",
        "badge": "Motion",
        "preview_text": "RISING TO THE TOP",
        "preview_highlight": "RISING"
    },
    "kinetic_drift": {
        "id": "kinetic_drift",
        "name": "Kinetic Drift Left",
        "category": "Kinetic",
        "fontname": "Bebas Neue, Montserrat",
        "fontsize": 70,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000FFFF&",
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 1,
        "italic": 0,
        "outline": 3.5,
        "shadow": 2.5,
        "alignment": 2,
        "margin_v": 80,
        "animation": "slide_up",
        "badge": "Motion",
        "preview_text": "DRIFT ACROSS SCREEN",
        "preview_highlight": "DRIFT"
    },
    "diagonal_rush": {
        "id": "diagonal_rush",
        "name": "Diagonal Velocity Rush",
        "category": "Kinetic",
        "fontname": "Impact, Anton",
        "fontsize": 72,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000A5FF&",
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 1,
        "italic": 1,
        "outline": 4.0,
        "shadow": 3.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "bounce",
        "badge": "Speed",
        "preview_text": "AT FULL SPEED",
        "preview_highlight": "SPEED"
    },
    "elevator_rise": {
        "id": "elevator_rise",
        "name": "Elevator Level Up",
        "category": "Kinetic",
        "fontname": "Montserrat, Inter",
        "fontsize": 64,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000FF00&",
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 1,
        "italic": 0,
        "outline": 3.0,
        "shadow": 2.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "slide_up",
        "badge": "Motion",
        "preview_text": "LEVEL UP DAILY",
        "preview_highlight": "LEVEL"
    },
    "velocity_swipe": {
        "id": "velocity_swipe",
        "name": "Velocity Fast Swipe",
        "category": "Kinetic",
        "fontname": "Anton, Montserrat",
        "fontsize": 74,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H00FF00EA&",
        "outline_color": "&H00000000&",
        "back_color": "&H90000000&",
        "bold": 1,
        "italic": 0,
        "outline": 4.0,
        "shadow": 3.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "slide_up",
        "badge": "Fast",
        "preview_text": "FAST AS LIGHTNING",
        "preview_highlight": "FAST"
    },
    "smooth_glide": {
        "id": "smooth_glide",
        "name": "Smooth Silk Glide",
        "category": "Kinetic",
        "fontname": "Poppins, Inter",
        "fontsize": 60,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0080FF00&",
        "outline_color": "&H00111111&",
        "back_color": "&H60000000&",
        "bold": 1,
        "italic": 0,
        "outline": 2.0,
        "shadow": 2.0,
        "alignment": 2,
        "margin_v": 75,
        "animation": "slide_up",
        "badge": "Clean",
        "preview_text": "Glide through seamlessly",
        "preview_highlight": "seamlessly"
    },
    "wave_ripple": {
        "id": "wave_ripple",
        "name": "Ocean Wave Ripple",
        "category": "Kinetic",
        "fontname": "Syne, Montserrat",
        "fontsize": 66,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H00FFFF00&",
        "outline_color": "&H00000088&",
        "back_color": "&H80000000&",
        "bold": 1,
        "italic": 0,
        "outline": 3.0,
        "shadow": 3.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "bounce",
        "badge": "Flow",
        "preview_text": "RIDE THE WAVE",
        "preview_highlight": "WAVE"
    },
    "roller_banner": {
        "id": "roller_banner",
        "name": "Roller Banner Spin",
        "category": "Kinetic",
        "fontname": "Bebas Neue, Impact",
        "fontsize": 75,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000FFFF&",
        "outline_color": "&H00000000&",
        "back_color": "&H90000000&",
        "bold": 1,
        "italic": 0,
        "outline": 4.5,
        "shadow": 3.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "slide_up",
        "badge": "Motion",
        "preview_text": "ROLLING THE WHEEL",
        "preview_highlight": "ROLLING"
    },
    "horizon_pan": {
        "id": "horizon_pan",
        "name": "Horizon Pan Cinematic",
        "category": "Kinetic",
        "fontname": "Oswald, Inter",
        "fontsize": 62,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000BFFF&",
        "outline_color": "&H00000000&",
        "back_color": "&H70000000&",
        "bold": 1,
        "italic": 0,
        "outline": 2.5,
        "shadow": 2.5,
        "alignment": 2,
        "margin_v": 80,
        "animation": "slide_up",
        "badge": "Pro",
        "preview_text": "TO THE HORIZON",
        "preview_highlight": "HORIZON"
    },
    "kinetic_shimmer": {
        "id": "kinetic_shimmer",
        "name": "Kinetic Shimmer Glow",
        "category": "Kinetic",
        "fontname": "Montserrat, Poppins",
        "fontsize": 68,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H00FFD700&",
        "outline_color": "&H00000000&",
        "back_color": "&H00D7FF00&",
        "bold": 1,
        "italic": 0,
        "outline": 3.5,
        "shadow": 5.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "glow_pulse",
        "badge": "Pro",
        "preview_text": "SHINE BRIGHT TODAY",
        "preview_highlight": "SHINE"
    },

    # ==========================================
    # 5. CINEMATIC & EDITORIAL (10)
    # ==========================================
    "cinematic_serif": {
        "id": "cinematic_serif",
        "name": "Cinematic Editorial Serif",
        "category": "Cinematic",
        "fontname": "Georgia, Playfair Display, serif",
        "fontsize": 62,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H00E0FFFF&",
        "outline_color": "&H00111111&",
        "back_color": "&H60000000&",
        "bold": 0,
        "italic": 1,
        "outline": 2.0,
        "shadow": 3.0,
        "alignment": 2,
        "margin_v": 90,
        "animation": "smooth_fade",
        "badge": "Pro",
        "preview_text": "The quick brown fox",
        "preview_highlight": "brown"
    },
    "royal_gold": {
        "id": "royal_gold",
        "name": "Royal Gold Majesty",
        "category": "Cinematic",
        "fontname": "Cinzel, Times New Roman, serif",
        "fontsize": 65,
        "primary_color": "&H00F5F5F5&",
        "secondary_color": "&H0000D7FF&",
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 1,
        "italic": 0,
        "outline": 3.0,
        "shadow": 4.0,
        "alignment": 2,
        "margin_v": 85,
        "animation": "smooth_fade",
        "badge": "Luxury",
        "preview_text": "BORN FOR GREATNESS",
        "preview_highlight": "GREATNESS"
    },
    "film_noir": {
        "id": "film_noir",
        "name": "Film Noir Shadow",
        "category": "Cinematic",
        "fontname": "Playfair Display, Georgia",
        "fontsize": 64,
        "primary_color": "&H00DDDDDD&",
        "secondary_color": "&H00FFFFFF&",
        "outline_color": "&H00000000&",
        "back_color": "&H90000000&",
        "bold": 1,
        "italic": 1,
        "outline": 3.0,
        "shadow": 5.0,
        "alignment": 2,
        "margin_v": 85,
        "animation": "smooth_fade",
        "badge": "Noir",
        "preview_text": "In the shadows of night",
        "preview_highlight": "shadows"
    },
    "vogue_editorial": {
        "id": "vogue_editorial",
        "name": "Vogue Fashion Editorial",
        "category": "Cinematic",
        "fontname": "Playfair Display, Didot, serif",
        "fontsize": 68,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H00000000&",
        "outline_color": "&H00FFFFFF&",
        "back_color": "&H50000000&",
        "bold": 0,
        "italic": 0,
        "outline": 1.5,
        "shadow": 2.0,
        "alignment": 2,
        "margin_v": 90,
        "animation": "smooth_fade",
        "badge": "Vogue",
        "preview_text": "Elegance in motion",
        "preview_highlight": "Elegance"
    },
    "gothic_strike": {
        "id": "gothic_strike",
        "name": "Gothic Monument",
        "category": "Cinematic",
        "fontname": "Cinzel, Georgia",
        "fontsize": 66,
        "primary_color": "&H00E0E0E0&",
        "secondary_color": "&H000000FF&",
        "outline_color": "&H00000000&",
        "back_color": "&H90000000&",
        "bold": 1,
        "italic": 0,
        "outline": 3.5,
        "shadow": 4.0,
        "alignment": 2,
        "margin_v": 85,
        "animation": "bounce",
        "badge": "Dark",
        "preview_text": "CARVED IN STONE",
        "preview_highlight": "STONE"
    },
    "velvet_whisper": {
        "id": "velvet_whisper",
        "name": "Velvet Whisper Soft",
        "category": "Cinematic",
        "fontname": "Georgia, serif",
        "fontsize": 58,
        "primary_color": "&H00F0F0F0&",
        "secondary_color": "&H00D8BFD8&",
        "outline_color": "&H00111111&",
        "back_color": "&H50000000&",
        "bold": 0,
        "italic": 1,
        "outline": 1.5,
        "shadow": 2.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "smooth_fade",
        "badge": "Soft",
        "preview_text": "Whisper to the wind",
        "preview_highlight": "wind"
    },
    "parchment_ink": {
        "id": "parchment_ink",
        "name": "Parchment Script Ink",
        "category": "Cinematic",
        "fontname": "Pacifico, cursive",
        "fontsize": 64,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000E5FF&",
        "outline_color": "&H001E1E1E&",
        "back_color": "&H70000000&",
        "bold": 0,
        "italic": 0,
        "outline": 2.5,
        "shadow": 3.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "smooth_fade",
        "badge": "Script",
        "preview_text": "Stories written by hand",
        "preview_highlight": "Stories"
    },
    "minimalist_swiss": {
        "id": "minimalist_swiss",
        "name": "Minimalist Swiss Grid",
        "category": "Cinematic",
        "fontname": "Inter, Helvetica, Arial",
        "fontsize": 56,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H000000FF&", # Red dot
        "outline_color": "&H00000000&",
        "back_color": "&HAA000000&",
        "bold": 1,
        "italic": 0,
        "outline": 1.5,
        "shadow": 1.5,
        "alignment": 2,
        "margin_v": 75,
        "animation": "clean",
        "badge": "Swiss",
        "preview_text": "Form follows function",
        "preview_highlight": "function"
    },
    "silver_screen": {
        "id": "silver_screen",
        "name": "Silver Screen 35mm",
        "category": "Cinematic",
        "fontname": "Cinzel, Montserrat",
        "fontsize": 62,
        "primary_color": "&H00E6E6FA&",
        "secondary_color": "&H00FFFFFF&",
        "outline_color": "&H00000000&",
        "back_color": "&H80000000&",
        "bold": 1,
        "italic": 0,
        "outline": 2.5,
        "shadow": 4.0,
        "alignment": 2,
        "margin_v": 85,
        "animation": "smooth_fade",
        "badge": "35mm",
        "preview_text": "THE SILVER SCREEN",
        "preview_highlight": "SILVER"
    },
    "nordic_frost": {
        "id": "nordic_frost",
        "name": "Nordic Frost Ice",
        "category": "Cinematic",
        "fontname": "Syne, Montserrat",
        "fontsize": 65,
        "primary_color": "&H00F0F8FF&",
        "secondary_color": "&H00FFFFE0&",
        "outline_color": "&H00000088&",
        "back_color": "&H00FFFF00&",
        "bold": 1,
        "italic": 0,
        "outline": 2.5,
        "shadow": 5.0,
        "alignment": 2,
        "margin_v": 85,
        "animation": "glow_pulse",
        "badge": "Ice",
        "preview_text": "COLD AS ICE",
        "preview_highlight": "ICE"
    },

    # ==========================================
    # 6. SPECIAL FX & GLITCH (10)
    # ==========================================
    "cyber_glitch": {
        "id": "cyber_glitch",
        "name": "Cyber Glitch Jitter",
        "category": "FX",
        "fontname": "Orbitron, Impact",
        "fontsize": 72,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H00FFFF00&",
        "outline_color": "&H00FF00EA&",
        "back_color": "&H0000FFFF&",
        "bold": 1,
        "italic": 0,
        "outline": 4.0,
        "shadow": 5.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "glow_pulse",
        "badge": "Glitch",
        "preview_text": "SYSTEM OVERRIDE",
        "preview_highlight": "OVERRIDE"
    },
    "typewriter_pulse": {
        "id": "typewriter_pulse",
        "name": "Typewriter Pulse",
        "category": "FX",
        "fontname": "Courier New, monospace",
        "fontsize": 58,
        "primary_color": "&H0000FF00&", # Terminal Green
        "secondary_color": "&H00FFFFFF&",
        "outline_color": "&H00003300&",
        "back_color": "&HAA000000&",
        "bold": 1,
        "italic": 0,
        "outline": 2.0,
        "shadow": 2.0,
        "alignment": 2,
        "margin_v": 75,
        "animation": "clean",
        "badge": "Code",
        "preview_text": "root@system: access granted",
        "preview_highlight": "granted"
    },
    "pixel_8bit": {
        "id": "pixel_8bit",
        "name": "Pixel 8-Bit Arcade",
        "category": "FX",
        "fontname": "Impact, Arial Black",
        "fontsize": 70,
        "primary_color": "&H0000FFFF&", # Yellow
        "secondary_color": "&H0000FF00&", # Green
        "outline_color": "&H00000000&",
        "back_color": "&H000000FF&",
        "bold": 1,
        "italic": 0,
        "outline": 5.0,
        "shadow": 4.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "comic_pop",
        "badge": "Retro",
        "preview_text": "READY PLAYER ONE",
        "preview_highlight": "PLAYER"
    },
    "comic_boom": {
        "id": "comic_boom",
        "name": "Comic Boom Bang",
        "category": "FX",
        "fontname": "Bangers, Impact",
        "fontsize": 80,
        "primary_color": "&H0000E5FF&",
        "secondary_color": "&H000000FF&",
        "outline_color": "&H00000000&",
        "back_color": "&H0000FFFF&",
        "bold": 1,
        "italic": 0,
        "outline": 5.5,
        "shadow": 4.0,
        "alignment": 2,
        "margin_v": 85,
        "animation": "comic_pop",
        "badge": "Boom",
        "preview_text": "KABOOM!",
        "preview_highlight": "KABOOM!"
    },
    "firestorm": {
        "id": "firestorm",
        "name": "Firestorm Blaze",
        "category": "FX",
        "fontname": "Impact, Arial Black",
        "fontsize": 75,
        "primary_color": "&H0000FFFF&", # Yellow
        "secondary_color": "&H000000FF&", # Red
        "outline_color": "&H00000088&",
        "back_color": "&H000022FF&",
        "bold": 1,
        "italic": 0,
        "outline": 4.5,
        "shadow": 6.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "fire_pulse",
        "badge": "Fire",
        "preview_text": "IGNITE THE FLAME",
        "preview_highlight": "IGNITE"
    },
    "ice_shiver": {
        "id": "ice_shiver",
        "name": "Ice Shiver Shard",
        "category": "FX",
        "fontname": "Montserrat, Syne",
        "fontsize": 68,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H00FFFF00&",
        "outline_color": "&H008B0000&",
        "back_color": "&H00FFFF00&",
        "bold": 1,
        "italic": 0,
        "outline": 3.0,
        "shadow": 5.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "glow_pulse",
        "badge": "Cold",
        "preview_text": "FROZEN IN TIME",
        "preview_highlight": "FROZEN"
    },
    "matrix_code": {
        "id": "matrix_code",
        "name": "Matrix Code Rain",
        "category": "FX",
        "fontname": "Courier New, Impact",
        "fontsize": 66,
        "primary_color": "&H0032CD32&",
        "secondary_color": "&H0000FF00&",
        "outline_color": "&H00002200&",
        "back_color": "&H0000FF00&",
        "bold": 1,
        "italic": 0,
        "outline": 3.0,
        "shadow": 4.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "glow_pulse",
        "badge": "Matrix",
        "preview_text": "FOLLOW THE RABBIT",
        "preview_highlight": "RABBIT"
    },
    "shadow_stalker": {
        "id": "shadow_stalker",
        "name": "Shadow Stalker Horror",
        "category": "FX",
        "fontname": "Impact, Arial Black",
        "fontsize": 76,
        "primary_color": "&H00222222&",
        "secondary_color": "&H000000FF&",
        "outline_color": "&H00FFFFFF&",
        "back_color": "&H000000FF&",
        "bold": 1,
        "italic": 0,
        "outline": 3.0,
        "shadow": 6.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "fire_pulse",
        "badge": "Dark",
        "preview_text": "DON'T LOOK BEHIND",
        "preview_highlight": "BEHIND"
    },
    "hologram_scan": {
        "id": "hologram_scan",
        "name": "Hologram Blue Beam",
        "category": "FX",
        "fontname": "Orbitron, Montserrat",
        "fontsize": 68,
        "primary_color": "&H00E0FFFF&",
        "secondary_color": "&H00FFBF00&",
        "outline_color": "&H008B0000&",
        "back_color": "&H00FFFF00&",
        "bold": 1,
        "italic": 0,
        "outline": 2.5,
        "shadow": 5.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "glow_pulse",
        "badge": "Holo",
        "preview_text": "TRANSMITTING DATA",
        "preview_highlight": "DATA"
    },
    "vhs_vintage": {
        "id": "vhs_vintage",
        "name": "VHS 1984 Tape",
        "category": "FX",
        "fontname": "Impact, Arial Black",
        "fontsize": 68,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000A5FF&",
        "outline_color": "&H00000088&",
        "back_color": "&H00FF00EA&",
        "bold": 1,
        "italic": 0,
        "outline": 3.5,
        "shadow": 4.0,
        "alignment": 2,
        "margin_v": 80,
        "animation": "comic_pop",
        "badge": "VHS",
        "preview_text": "PLAY >> 1984",
        "preview_highlight": "PLAY"
    },

    # ==========================================
    # 7. CLEAN, MONOLINE & BADGES (6)
    # ==========================================
    "minimal_monoline": {
        "id": "minimal_monoline",
        "name": "Minimal Dark Pill Badge",
        "category": "Clean",
        "fontname": "Segoe UI, Inter, Helvetica, sans-serif",
        "fontsize": 54,
        "primary_color": "&H00F0F0F0&",
        "secondary_color": "&H0080FF00&",
        "outline_color": "&H00101010&",
        "back_color": "&HAA000000&",
        "bold": 0,
        "italic": 0,
        "outline": 1.5,
        "shadow": 1.0,
        "alignment": 2,
        "margin_v": 70,
        "animation": "clean",
        "badge": "Clean",
        "preview_text": "The quick monoline",
        "preview_highlight": "monoline"
    },
    "translucent_box": {
        "id": "translucent_box",
        "name": "Translucent Frosted Box",
        "category": "Clean",
        "fontname": "Poppins, Inter",
        "fontsize": 56,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000FFFF&",
        "outline_color": "&H00000000&",
        "back_color": "&H881E1E1E&",
        "bold": 1,
        "italic": 0,
        "outline": 1.0,
        "shadow": 2.0,
        "alignment": 2,
        "margin_v": 75,
        "animation": "clean",
        "badge": "Modern",
        "preview_text": "Frosted glass aesthetic",
        "preview_highlight": "glass"
    },
    "yellow_badge": {
        "id": "yellow_badge",
        "name": "Yellow Highlighter Tape",
        "category": "Clean",
        "fontname": "Montserrat, Impact",
        "fontsize": 62,
        "primary_color": "&H00000000&", # Black text
        "secondary_color": "&H00000000&",
        "outline_color": "&H00000000&",
        "back_color": "&H0000FFFF&", # Bright Yellow Tape
        "bold": 1,
        "italic": 0,
        "outline": 0.0,
        "shadow": 0.0,
        "alignment": 2,
        "margin_v": 75,
        "animation": "micro_bounce",
        "badge": "Tape",
        "preview_text": "HIGHLIGHTED THOUGHTS",
        "preview_highlight": "HIGHLIGHTED"
    },
    "modern_underline": {
        "id": "modern_underline",
        "name": "Modern Accent Underline",
        "category": "Clean",
        "fontname": "Inter, Poppins",
        "fontsize": 58,
        "primary_color": "&H00FFFFFF&",
        "secondary_color": "&H0000FFFF&",
        "outline_color": "&H00151515&",
        "back_color": "&H50000000&",
        "bold": 1,
        "italic": 0,
        "outline": 2.0,
        "shadow": 1.5,
        "alignment": 2,
        "margin_v": 75,
        "animation": "clean",
        "badge": "Clean",
        "preview_text": "Underlined focus word",
        "preview_highlight": "focus"
    },
    "corner_stamp": {
        "id": "corner_stamp",
        "name": "Corner Stamp Watermark",
        "category": "Clean",
        "fontname": "Bebas Neue, Montserrat",
        "fontsize": 48,
        "primary_color": "&H00CCCCCC&",
        "secondary_color": "&H00FFFFFF&",
        "outline_color": "&H00000000&",
        "back_color": "&H70000000&",
        "bold": 0,
        "italic": 0,
        "outline": 1.5,
        "shadow": 1.0,
        "alignment": 1, # Bottom Left
        "margin_v": 50,
        "animation": "clean",
        "badge": "Stamp",
        "preview_text": "OFFICIAL BROADCAST",
        "preview_highlight": "OFFICIAL"
    },
    "none": {
        "id": "none",
        "name": "No Captions (Clean Footage)",
        "category": "Clean",
        "fontname": "",
        "fontsize": 0,
        "primary_color": "",
        "secondary_color": "",
        "outline_color": "",
        "back_color": "",
        "bold": 0,
        "italic": 0,
        "outline": 0,
        "shadow": 0,
        "alignment": 2,
        "margin_v": 0,
        "animation": "none",
        "badge": "Clean",
        "preview_text": "Clean video without text",
        "preview_highlight": ""
    }
}

def get_template(template_id: str) -> dict:
    return TEMPLATES.get(template_id, TEMPLATES["hormozi_classic"])

def build_ass_header(template_id: str, width: int = 1920, height: int = 1080, font_override: str = None) -> str:
    tpl = get_template(template_id)
    if tpl["id"] == "none":
        return ""

    fontname = font_override if font_override else tpl['fontname']

    header = f"""[Script Info]
Title: SynchroClip Dynamic Subtitles
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709
PlayResX: {width}
PlayResY: {height}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,{fontname},{tpl['fontsize']},{tpl['primary_color']},{tpl['secondary_color']},{tpl['outline_color']},{tpl['back_color']},{tpl['bold']},{tpl['italic']},0,0,100,100,0,0,1,{tpl['outline']},{tpl['shadow']},{tpl['alignment']},40,40,{tpl['margin_v']},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
    return header
